version: "3.4"
services:

    fullcycle_db:
        build:
          context: ./mysql
          dockerfile: Dockerfile
        image: renan79/fullcycle_db:prod
        command: --innodb-use-native-aio=0
        container_name: fullcycle_db
        restart: always
        tty: true
        volumes:
          - ./mysql/data/:/var/lib/mysql
          - ./mysql/dump/:/docker-entrypoint-initdb.d/
        environment:
          - MYSQL_ROOT_PASSWORD=docker
          - MYSQL_USER=docker
          - MYSQL_PASSWORD=docker
          - MYSQL_DATABASE=fullcycleDB
        ports:
          - "3306:3306"
        networks:
          - fullcycle_net
    
    fullcycle_app:
        build: 
          context: ./node
          dockerfile: Dockerfile.prod
        image: renan79/fullcycle_app:prod
        container_name: fullcycle_app
        depends_on:
          - fullcycle_db
        ports:
          - "3000:3000"
        networks:
          - fullcycle_net

    fullcycle_nginx:
        build:
          context: ./nginx
          dockerfile: Dockerfile.prod
        image: renan79/fullcycle_nginx:prod
        container_name: fullcycle_nginx
        depends_on: 
          - fullcycle_app
          - fullcycle_db
        ports:
          - "8080:80"
        networks:
          - fullcycle_net
    
networks:
  fullcycle_net:
    driver: bridge