version: '3.8'
services:

    fullcycle_db:
        build:
          context: ./mysql
          dockerfile: Dockerfile
        image: renan79/fullcycle_db:prod        
        command: --innodb-use-native-aio=0
        container_name: fullcycle_db
        restart: always
        tty: true
        volumes:
          - mysql-data:/var/lib/mysql
          - mysql-dump:/docker-entrypoint-initdb.d/
        environment:
          - MYSQL_ROOT_PASSWORD=docker
          - MYSQL_USER=docker
          - MYSQL_PASSWORD=docker
          - MYSQL_DATABASE=fullcycleDB
        ports:
          - "3306:3306"
        networks:
          - fullcycle_net
    
    fullcycle_app:
        build: 
          context: ./node
          dockerfile: Dockerfile.prod
        image: renan79/fullcycle_app:prod        
        container_name: fullcycle_app
        entrypoint: dockerize -wait tcp://fullcycle_db:3306 -timeout 20s docker-entrypoint.sh
        command: sh -c "npm install & npm start"
        volumes:
          - app:/usr/src/app
        depends_on:
          - fullcycle_db
        networks:
          - fullcycle_net

    fullcycle_nginx:
        build:
          context: ./nginx
          dockerfile: Dockerfile.prod
        image: renan79/fullcycle_nginx:prod        
        container_name: fullcycle_nginx        
        ports:
          - "8080:80"
        networks:
          - fullcycle_net
    
networks:
  fullcycle_net:
    name: fullcycle_net
    driver: bridge

volumes:
  mysql-data:
  mysql-dump:
  app: