FROM nginx:1.25.3 as builder

RUN rm /usr/share/nginx/html -rf

COPY html /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d

FROM nginx:1.26.1-alpine

WORKDIR /usr/share/nginx/html

COPY --from=builder  /usr/share/nginx/html .

EXPOSE 8080

ENTRYPOINT [ "/docker-entrypoint.sh" ]

CMD [ "nginx", "-g", "daemon off;" ]